{den, ...}: {
  # Zagreus host with user Lorenzo.
  # It will automatically create a den.aspects.zagreus and den.aspects.lorenzo
  den.hosts.x86_64-linux.zagreus.users.lorenzo = {};

  den.aspects.zagreus = {
    includes = with den.aspects; [
      base
      boot.plymouth
      hardware.cpu-amd
      hardware.igpu-amd
      hardware.firmware
      hardware.btrfs
      networking
      networking.networkmanager
      networking.firewall
      networking.tailscale
      theming.catppuccin
      desktop.bluetooth
      desktop.hyprland
      desktop.gaming
      desktop.messaging
      desktop.work
      desktop.bambu-studio
      development
      docker
    ];

    nixos = {
      hardware.facter.reportPath = ./facter.json;

      boot.loader.limine.extraEntries = ''
        /CachyOS
            comment: Chainload CachyOS's own limine bootloader
            protocol: efi
            path: guid(a19d13ab-1f78-4bf8-8e0f-c5c9f33d8217):/EFI/limine/limine_x64.efi
      '';

      # A large parallel C++ build (e.g. bambu-studio) with no cap ran the machine
      # out of RAM+swap and froze it solid, requiring a hard reset. Cage the build
      # daemon's cgroup so a runaway build gets throttled/OOM-killed on its own
      # instead of starving the interactive desktop session. Sized for zagreus's 27G.
      systemd.services.nix-daemon.serviceConfig = {
        MemoryHigh = "18G";
        MemoryMax = "22G";
      };
    };

    homeManager = {
      xdg.configFile."hyprmoncfg/profiles/home-dual.conf".text = ''
        # Generated by hyprmoncfg

        monitorv2 {
          output = desc:Audio Processing Technology  Ltd HDMI 0x00000055
          mode = 2880x1800@100.00
          position = 540x1728
          scale = 1.5
          sdr_min_luminance = 0.2
          sdr_max_luminance = 80
        }

        monitorv2 {
          output = desc:Samsung Electric Company Odyssey G80SD H1AK500000
          mode = 3840x2160@119.88
          position = 0x0
          scale = 1.25
          vrr = 1
          bitdepth = 10
          sdr_min_luminance = 0.2
          sdr_max_luminance = 80
        }

        workspace = 1, monitor:desc:Samsung Electric Company Odyssey G80SD H1AK500000, default:true, persistent:true
        workspace = 2, monitor:desc:Samsung Electric Company Odyssey G80SD H1AK500000
        workspace = 3, monitor:desc:Samsung Electric Company Odyssey G80SD H1AK500000
        workspace = 4, monitor:desc:Samsung Electric Company Odyssey G80SD H1AK500000
        workspace = 5, monitor:desc:Samsung Electric Company Odyssey G80SD H1AK500000
        workspace = 6, monitor:desc:Audio Processing Technology  Ltd HDMI 0x00000055, default:true, persistent:true
        workspace = 7, monitor:desc:Audio Processing Technology  Ltd HDMI 0x00000055
        workspace = 8, monitor:desc:Audio Processing Technology  Ltd HDMI 0x00000055
        workspace = 9, monitor:desc:Audio Processing Technology  Ltd HDMI 0x00000055
        workspace = 10, monitor:desc:Audio Processing Technology  Ltd HDMI 0x00000055
      '';

      xdg.configFile."hyprmoncfg/profiles/home-dual.lua".text = ''
        -- Generated by hyprmoncfg

        hl.monitor({
          output = "desc:Audio Processing Technology  Ltd HDMI 0x00000055",
          mode = "2880x1800@100.00",
          position = "540x1728",
          scale = 1.5,
          sdr_min_luminance = 0.2,
          sdr_max_luminance = 80,
        })

        hl.monitor({
          output = "desc:Samsung Electric Company Odyssey G80SD H1AK500000",
          mode = "3840x2160@119.88",
          position = "0x0",
          scale = 1.25,
          vrr = 1,
          bitdepth = 10,
          sdr_min_luminance = 0.2,
          sdr_max_luminance = 80,
        })

        hl.workspace_rule({ workspace = "1", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000", default = true, persistent = true })
        hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
        hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
        hl.workspace_rule({ workspace = "4", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
        hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
        hl.workspace_rule({ workspace = "6", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055", default = true, persistent = true })
        hl.workspace_rule({ workspace = "7", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
        hl.workspace_rule({ workspace = "8", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
        hl.workspace_rule({ workspace = "9", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
        hl.workspace_rule({ workspace = "10", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
      '';

      xdg.configFile."hyprmoncfg/profiles/home-dual.json".text = ''
        {
          "name": "home-dual",
          "created_at": "2026-07-19T18:16:54.34538402Z",
          "updated_at": "2026-07-19T18:32:01.137213459Z",
          "outputs": [
            {
              "key": "audio processing technology ltd|hdmi|0x00000055",
              "match_key": "audio processing technology ltd|hdmi|0x00000055",
              "name": "HDMI-A-1",
              "description": "Audio Processing Technology  Ltd HDMI 0x00000055",
              "make": "Audio Processing Technology  Ltd",
              "model": "HDMI",
              "serial": "0x00000055",
              "enabled": true,
              "mode": "2880x1800@100.00Hz",
              "width": 2880,
              "height": 1800,
              "refresh": 100,
              "x": 540,
              "y": 1728,
              "scale": 1.5,
              "transform": 0,
              "bitdepth": 8,
              "cm": "srgb",
              "sdr_brightness": 1,
              "sdr_saturation": 1,
              "sdr_min_luminance": 0.2,
              "sdr_max_luminance": 80,
              "min_luminance": 0
            },
            {
              "key": "samsung electric company|odyssey g80sd|h1ak500000",
              "match_key": "samsung electric company|odyssey g80sd|h1ak500000",
              "name": "DP-1",
              "description": "Samsung Electric Company Odyssey G80SD H1AK500000",
              "make": "Samsung Electric Company",
              "model": "Odyssey G80SD",
              "serial": "H1AK500000",
              "enabled": true,
              "mode": "3840x2160@119.88Hz",
              "width": 3840,
              "height": 2160,
              "refresh": 119.88,
              "x": 0,
              "y": 0,
              "scale": 1.25,
              "vrr": 1,
              "transform": 0,
              "bitdepth": 10,
              "cm": "srgb",
              "sdr_brightness": 1,
              "sdr_saturation": 1,
              "sdr_min_luminance": 0.2,
              "sdr_max_luminance": 80,
              "min_luminance": 0
            }
          ],
          "workspaces": {
            "enabled": true,
            "strategy": "sequential",
            "max_workspaces": 10,
            "group_size": 5,
            "monitor_order": [
              "samsung electric company|odyssey g80sd|h1ak500000",
              "audio processing technology ltd|hdmi|0x00000055"
            ]
          },
          "exec": ""
        }
      '';
    };
  };
}
