{flake, ...}: {
  imports = [
    flake.inputs.dms.homeModules.dank-material-shell
    flake.inputs.dms.homeModules.niri
    flake.inputs.dms-plugin-registry.modules.default
    ./dms-settings.nix
  ];

  programs.dank-material-shell = {
    enable = true;

    systemd = {
      enable = true;
      restartIfChanged = true;
    };

    niri.includes = {
      enable = true; # Enable config includes hack. Enabled by default.

      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        # "alttab" # Please note that niri will throw an error if any of these files are missing.
        # "binds"
        # "layout"
        "outputs"
        "wpblur"
      ];
    };

    enableSystemMonitoring = true;
    enableDynamicTheming = false;
    enableAudioWavelength = false;
    enableCalendarEvents = true;
    enableClipboardPaste = true;

    session = {
      isLightMode = false;
      weatherCoordinates = "41.4595261,13.0125912";
    };

    plugins = {
      dockerManager.enable = true;
      homeAssistantMonitor.enable = true;
      powerOptions.enable = true;
      dankPomodoroTimer.enable = true;
      tailscale.enable = true;
    };
  };
}
