{
  den,
  lib,
  ...
}: {
  den.aspects.desktop.hyprland = {
    includes = with den.aspects; [
      desktop
      desktop.wm
      desktop.base-applications
      desktop.wm-applications
      desktop.wlr-which-key
      desktop.noctalia-greeter
      desktop.noctalia
      desktop.wlr-which-key
    ];

    nixos = {
      inputs',
      pkgs,
      ...
    }: {
      environment.systemPackages = with pkgs; [
        runapp
        hyprmoncfg
      ];

      programs.hyprland = {
        enable = true;
        withUWSM = true;

        package = inputs'.hyprland.packages.hyprland;
        portalPackage = inputs'.hyprland.packages.xdg-desktop-portal-hyprland;
      };
    };

    homeManager = {
      pkgs,
      config,
      osConfig,
      self',
      inputs',
      ...
    }: {
      home.packages = [self'.packages.system-action];

      home.sessionVariables = {
        QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
        ELECTRON_OZONE_PLATFORM_HINT = "auto";

        GDK_BACKEND = "wayland";
        QT_QPA_PLATFORM = "wayland;xcb";
        SDL_VIDEODRIVER = "wayland";
        CLUTTER_BACKEND = "wayland";

        UWSM_MANAGED = "1";
      };

      xdg.configFile."uwsm/env".source = "${config.home.sessionVariablesPackage}/etc/profile.d/hm-session-vars.sh";

      wayland.windowManager.hyprland = {
        enable = true;
        systemd.enable = false;
        systemd.enableXdgAutostart = true;
        xwayland.enable = true;

        # set the Hyprland and XDPH packages to null to use the ones from the NixOS module
        package = null;
        portalPackage = null;

        configType = "lua";
        extraLuaFiles = {
          "input" = ./config/input.lua;
          "keybinds" = ./config/keybinds.lua;
          "rules" = ./config/rules.lua;
          "style" = ./config/style.lua;
          "fonts" = {
            autoLoad = false;
            content = ''
              return {
                serif = "${osConfig.fonts.serif}",
                sans = "${osConfig.fonts.sans}",
                mono = "${osConfig.fonts.mono}",
                nerd = "${osConfig.fonts.nerd}",
              }
            '';
          };
          "programs" = {
            autoLoad = false;
            content = ''
              return {
                _1password = "${lib.getExe pkgs._1password-gui}",
                terminal = "${lib.getExe pkgs.ghostty}",
                browser = "${lib.getExe inputs'.helium.packages.default}",
                file_manager = "${lib.getExe pkgs.nautilus}",
                yazi = "${lib.getExe pkgs.yazi}",
                bluetui = "${lib.getExe pkgs.bluetui}",
                wiremix = "${lib.getExe pkgs.wiremix}",
                quick_terminal = "${lib.getExe self'.packages.quick-terminal}",
                system_action = "${lib.getExe self'.packages.system-action}",
                runapp = "${lib.getExe pkgs.runapp}",
                wlr_which_key = "${lib.getExe pkgs.wlr-which-key}",
              }
            '';
          };
        };
        extraConfig = ''
          require("colors")

          -- monitors.lua is generated by hyprmoncfg, so it may not exist yet
          require("monitors")
        '';
      };

      programs.hyprland-qt-support.enable = true;

      systemd.user.services.hyprmoncfgd = {
        Unit = {
          Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
          After = [config.wayland.systemd.target];
          PartOf = [config.wayland.systemd.target];
        };
        Service = {
          Type = "simple";
          ExecStart = lib.getExe' pkgs.hyprmoncfg "hyprmoncfgd";
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [config.wayland.systemd.target];
      };
    };
  };
}
