{
  den,
  lib,
  ...
}: {
  den.aspects.desktop.hyprland = {
    includes = with den.aspects; [
      desktop
      desktop.wm
      desktop.base-applications
      desktop.agnostic-applications
      desktop.noctalia-greeter
      desktop.noctalia
    ];

    nixos = {
      inputs',
      pkgs,
      ...
    }: {
      environment.systemPackages = with pkgs; [
        runapp
        hyprmoncfg
      ];

      programs.hyprland = {
        enable = true;
        withUWSM = true;

        package = inputs'.hyprland.packages.hyprland;
        portalPackage = inputs'.hyprland.packages.xdg-desktop-portal-hyprland;
      };
    };

    homeManager = {
      pkgs,
      config,
      self',
      ...
    }: {
      home.packages = [self'.packages.system-action];

      # start all wayland home-manager services (noctalia, hyprmoncfgd, ...) with Hyprland
      wayland.systemd.target = "hyprland-session.target";

      # xdg.configFile."hypr/vars.lua".text = ''
      #   return {
      #     terminal = "${lib.getExe pkgs.alacritty}",
      #     browser = "${lib.getExe inputs'.helium.packages.default}",
      #     file_manager = "${lib.getExe pkgs.nautilus}",
      #     yazi = "${lib.getExe pkgs.yazi}",
      #     bluetui = "${lib.getExe pkgs.bluetui}",
      #   }
      # '';

      wayland.windowManager.hyprland = {
        enable = true;
        systemd.enable = true;
        systemd.enableXdgAutostart = true;
        xwayland.enable = true;

        # set the Hyprland and XDPH packages to null to use the ones from the NixOS module
        package = null;
        portalPackage = null;

        configType = "lua";
        extraLuaFiles = {
          "input" = ./config/input.lua;
          "keybinds" = ./config/keybinds.lua;
          "rules" = ./config/rules.lua;
          "style" = ./config/style.lua;
        };
        extraConfig = ''
          require("keybinds")
          require("rules")
          require("input")
          require("style")

          -- monitors.lua is generated by hyprmoncfg, so it may not exist yet
          pcall(require, "monitors")
        '';
      };

      programs.hyprland-qt-support.enable = true;

      systemd.user.services.hyprmoncfgd = {
        Unit = {
          Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
          After = [config.wayland.systemd.target];
          PartOf = [config.wayland.systemd.target];
        };
        Service = {
          Type = "simple";
          ExecStart = lib.getExe' pkgs.hyprmoncfg "hyprmoncfgd";
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [config.wayland.systemd.target];
      };
    };
  };
}
