-- Generated by hyprmoncfg

hl.monitor({
	output = "desc:Audio Processing Technology  Ltd HDMI 0x00000055",
	mode = "2880x1800@100.00",
	position = "540x1728",
	scale = 1.5,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.monitor({
	output = "desc:Samsung Electric Company Odyssey G80SD H1AK500000",
	mode = "3840x2160@119.88",
	position = "0x0",
	scale = 1.25,
	vrr = 1,
	bitdepth = 10,
	sdr_min_luminance = 0.2,
	sdr_max_luminance = 80,
})

hl.workspace_rule({
	workspace = "1",
	monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000",
	default = true,
	persistent = true,
})
hl.workspace_rule({ workspace = "2", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Samsung Electric Company Odyssey G80SD H1AK500000" })
hl.workspace_rule({
	workspace = "6",
	monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055",
	default = true,
	persistent = true,
})
hl.workspace_rule({ workspace = "7", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Audio Processing Technology  Ltd HDMI 0x00000055" })
