-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1",
  mode = "2880x1920@120.00",
  position = "5360x780",
  scale = 1.5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Xiaomi Corporation Mi Monitor 0000000000000",
  mode = "3440x1440@99.99",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Xiaomi Corporation Mi Monitor 0000000000000" })
hl.workspace_rule({ workspace = "6", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "8", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "9", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
hl.workspace_rule({ workspace = "10", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1" })
